### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sebslight** [draivin/hscopes#1]
- Issue Type: `Performance`
- Extension Name: `hscopes`
- Extension Version: `0.0.6`
- OS Version: `Darwin arm64 20.5.0`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/97/v48kmmpn7dj2_7zwycmcdfbm0000gn/T/draivin.hscopes-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[draivin.hscopes-unresponsive.txt](https://github.com/draivin/hscopes/files/6682773/draivin.hscopes-unresponsive.txt)

**Comment by draivin** [comment]
Thanks for reporting the issue, I had a suspicion that the new context related features might cause some performance issues. I'll take a look into it, and if there is no better way, I'll probably add a configuration option so the context features can be disabled.

**Comment by JuanG970** [comment]
Hello, I am having the same issue, basically vscode freeze a few seconds, this is the Log I get.

```
[warning] UNRESPONSIVE extension host: 'draivin.hscopes' took 99% of 5321.154ms, saved PROFILE here: 'file:///var/folders/kp/4x7mf2qj67x2vc5rknxpg9p00000gn/T/exthost-5407d4.cpuprofile' [{"id":"draivin.hscopes","total":5283172,"percentage":99},{"id":"gc","total":37894,"percentage":1}]
```

**Comment by sleepymalc** [comment]
Same here. I love how hsnips works, but this is really annoying to get stuck (no response for typing) for like every 5 minutes. Love to see any improvement!

**Comment by draivin** [comment]
Should be mostly fixed on latest version, if it still happens please let me know.
