### ISSUE TITLE
Scopes doesn't match textmate

### ISSUE THREAD

**Issue by MKMatriX** [draivin/hscopes#2]
![image](https://user-images.githubusercontent.com/21899397/129984865-b7e20d5b-0be3-424c-b8ef-ada3935e3573.png)
Textmate scopes = ["text.html.php"]
And from hyperSnips I get ["source.php", "constant.other.php"] so I can't get my snippet work in html embed to php. Also there are some errors in console.

**Comment by draivin** [comment]
If this is still relevant, could you reopen and share some code that reproduces this issue?
