### ISSUE TITLE
Does this extension use existing text parser for VSCode?

### ISSUE THREAD

**Issue by haberdashPI** [draivin/hscopes#4]
My main concern with making use of this extension are the performance implications of every single extension that wants to access tokens re-parsing a file. This really feels like something that VSCode should have an API for, rather than each extension implementing "itself" (e.g. by importing this library).

Does this extension re-parse the text for you, or does it access something internal to VSCode that gives you the desired scope information?

I think this is something you should address in the README.

**Comment by draivin** [comment]
It does reparse every file, but the intent of having this logic in an separate extension, is that you can use it as a dependency, so it only needs to reparse the file once, and it will have the data ready for any extension that depends on it, be it one or many.

**Comment by haberdashPI** [comment]
Hi @draivin, I'm not sure I understand.

Here's my understanding: generally the way you include a library as part of an extension is via a bundler such as webpack. This means that each extension using hscopes has a different instance of the library bundled with it. They will each, separately have to parse the file.

Is there some way you've found to work around this limitation or is my understanding mistaken? Do you have reference regarding the correct understanding?

**Comment by haberdashPI** [comment]
To be clear, the reason why I'm pushing on this so much is that I really am excited by the possibility of using this library, and would love it if it made sense to use. So I really appreciate your efforts to do this.

Once I do understand, I will at least make a PR to add some clarifying language to the README, if you are alright with that.

**Comment by draivin** [comment]
Sorry for the delay.

What I mean when I say dependency is not a typescript dependency, but a vscode extension dependency, you can learn more about this by checking the field `extensionDependencies` on the [vscode documentation](https://code.visualstudio.com/api/references/extension-manifest). But put simply, the way it works is that it actually install this package as a separate package, and then it is up to your program to interact with the installed dependency, which can be done as shown in the example:

```ts
async function example(doc : vscode.TextDocument, pos: vscode.Position) : void {
  const hs = vscode.extensions.getExtension('draivin.hscopes');
  const token : scopeInfo.Token = hs.getScopeAt(doc, pos);
}
```

To be clear, none of the code of this extension should be included or re-bundled on your own extension, as that does not allow parsing re-use.

**Comment by haberdashPI** [comment]
Ah, somehow I missed that. Thank you @draivin. I'll definitely use this then! Thanks for your work on this.

I'll make a PR to add a bit of language to the README about this (though I recognize that if I had scrutinized that example a little longer I might have figured this out by myself 😳 )
