### ISSUE TITLE
Bug & Feature request:  add `Forcibly reload scopes` command for scope match error

### ISSUE THREAD

**Issue by yfzhao20** [draivin/hscopes#6]
I found that if I delete a whole line by using <kbd>ctrl+shift+k</kbd>, hscopes will give wrong match results. You can reproduce the bug by:

1. install `draivin.hsnips` & `dravin.hscopes`
2. add this code to `markdown.hsnips`
```js
global
const vscode = require('vscode');
vscode.window.onDidChangeTextEditorSelection((e) => {
    console.log(vscode.extensions.getExtension('draivin.hscopes').exports.getScopeAt(e.textEditor.document, e.selections[0].active).scopes.toString())
});
endglobal
```
3. new a `.md` file and open execute `Developer : toggle developer tools`, then open console. 
4. Execute `reload snippets`. Then the result is shown below:

https://user-images.githubusercontent.com/80528249/156931067-071d0583-2de2-425e-b519-6aa5f48a625d.mp4

I think that it is a good idea to add a command "reload scopes". I used to write markdown with `draivin.hsnips` but it randomly matches wrong scopes. Without the command "reload scopes", maybe we have to reload VSCode to get rid of the error.

Thanks! 😃

**Comment by draivin** [comment]
Thanks for the feedback, I'm a little busy right now, but I'll look into it early next week!

**Comment by DedZago** [comment]
Is there any update on this? I think this is closely related to [this HyperSnips issue](https://github.com/draivin/hsnips/issues/122) and fixing it would improve the workflow for markdown users.

**Comment by draivin** [comment]
I have updated the cache logic so it should break less often, nevertheless, there is now a command to forcibly reload the scopes for the current editor.
