### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Msadat97** [draivin/hscopes#7]
Hi. Thank you for your great extensions.

I have a question regarding the performance of this extension. I was wondering why the extension is named as unresponsive by VSCODE in the running extension panel. It causes the hsnip to result in significant delay when editing the settings.json file. 

Thanks in advance.

**Comment by draivin** [comment]
Should be fixed on latest version, if it still happens please let me know.

**Comment by sanpoyur** [comment]
This still happens for Linux users. Quickly replacing `\\` by `/` in `blacklist` defined in `extension.ts` solves this problem.
