### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by xufromxu** [draivin/hscopes#8]
- Issue Type: `Bug`
- Extension Name: `hscopes`
- Extension Version: `0.0.6`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7,
		"activateCallTime": 2,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "grasspy.autopunc",
				"_lower": "grasspy.autopunc"
			},
			"activationEvent": "api"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by draivin** [comment]
Should be fixed on latest version, if it still happens please let me know.
