### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by asoow** [draivin/hscopes#9]
- Issue Type: `Bug`
- Extension Name: `hscopes`
- Extension Version: `0.0.6`
- OS Version: `Darwin x64 21.1.0`
- VS Code version: `1.70.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by draivin** [comment]
Hi, you should probably paste what was written to your clipboard, as it currently stands this issue can not be acted upon, since it doesn't have any data.
